-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.asana;

CREATE TABLE IF NOT EXISTS public.asana
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    name bpchar NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.chakra;

CREATE TABLE IF NOT EXISTS public.chakra
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    name bpchar NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.teacher;

CREATE TABLE IF NOT EXISTS public.teacher
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    name bpchar NOT NULL,
    PRIMARY KEY (id)
);
END;